import type { Product, User, Purchase } from "./types"

export const mockVendors: User[] = [
  {
    id: "v1",
    email: "sarah@college.edu",
    name: "Sarah Johnson",
    role: "vendor",
    walletBalance: 2500,
    avatar: "/college-student-woman.png",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "v2",
    email: "mike@college.edu",
    name: "Mike Chen",
    role: "vendor",
    walletBalance: 1800,
    avatar: "/college-student-man.jpg",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "v3",
    email: "emma@college.edu",
    name: "Emma Davis",
    role: "vendor",
    walletBalance: 3200,
    avatar: "/college-student-woman-2.jpg",
    createdAt: new Date("2024-01-20"),
  },
]

export const mockProducts: Product[] = [
  {
    id: "p1",
    vendorId: "v1",
    vendorName: "Sarah Johnson",
    name: "Wireless Earbuds",
    description: "High-quality wireless earbuds with noise cancellation",
    price: 45,
    category: "Electronics",
    image: "/wireless-earbuds.png",
    images: [
      "/wireless-headphones.png",
      "/wireless-headphones-front.png",
      "/wireless-headphones-side.png",
      "/wireless-headphones-case.png",
    ],
    stock: 15,
    sold: 23,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "p2",
    vendorId: "v1",
    vendorName: "Sarah Johnson",
    name: "USB-C Cable",
    description: "Durable 6ft USB-C charging cable",
    price: 12,
    category: "Electronics",
    image: "/usb-cable.png",
    images: ["/usb-cable.png"],
    stock: 30,
    sold: 45,
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "p3",
    vendorId: "v2",
    vendorName: "Mike Chen",
    name: "Vintage T-Shirt",
    description: "Retro college graphic tee, size M",
    price: 18,
    category: "Fashion",
    image: "/vintage-tshirt.jpg",
    images: ["/vintage-tshirt.jpg"],
    stock: 8,
    sold: 12,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "p4",
    vendorId: "v2",
    vendorName: "Mike Chen",
    name: "Denim Jacket",
    description: "Classic blue denim jacket, gently used",
    price: 35,
    category: "Fashion",
    image: "/classic-denim-jacket.png",
    images: [
      "/classic-denim-jacket.png",
      "/denim-jacket-front.jpg",
      "/denim-jacket-back.png",
      "/denim-jacket-detail.png",
    ],
    stock: 3,
    sold: 7,
    createdAt: new Date("2024-02-12"),
  },
  {
    id: "p5",
    vendorId: "v3",
    vendorName: "Emma Davis",
    name: "Calculus Textbook",
    description: "Calculus II textbook, latest edition with practice problems",
    price: 60,
    category: "Books",
    image: "/calculus-textbook.png",
    images: ["/calculus-textbook.png"],
    stock: 2,
    sold: 18,
    createdAt: new Date("2024-01-25"),
  },
  {
    id: "p6",
    vendorId: "v3",
    vendorName: "Emma Davis",
    name: "Tutoring Session",
    description: "One-on-one math tutoring session (1 hour)",
    price: 25,
    category: "Services",
    image: "/tutoring-session.png",
    images: ["/tutoring-session.png"],
    stock: 20,
    sold: 34,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "p7",
    vendorId: "v1",
    vendorName: "Sarah Johnson",
    name: "Laptop Stand",
    description: "Adjustable aluminum laptop stand",
    price: 28,
    category: "Electronics",
    image: "/laptop-stand.png",
    images: ["/laptop-stand.png", "/laptop-stand-front.jpg", "/laptop-stand-angle.jpg"],
    stock: 10,
    sold: 15,
    createdAt: new Date("2024-02-08"),
  },
  {
    id: "p8",
    vendorId: "v2",
    vendorName: "Mike Chen",
    name: "Sneakers",
    description: "White sneakers, size 10, like new",
    price: 42,
    category: "Fashion",
    image: "/white-sneakers.png",
    images: ["/diverse-sneaker-collection.png", "/sneakers-side.jpg", "/sneakers-top.jpg", "/sneakers-sole.jpg"],
    stock: 1,
    sold: 5,
    createdAt: new Date("2024-02-15"),
  },
]

export const mockCustomer: User = {
  id: "c1",
  email: "alex@college.edu",
  name: "Alex Martinez",
  role: "customer",
  walletBalance: 150,
  avatar: "/diverse-college-students.png",
  createdAt: new Date("2024-01-10"),
}

export const mockCustomers: User[] = [
  {
    id: "c1",
    email: "alex@college.edu",
    name: "Alex Martinez",
    role: "customer",
    walletBalance: 150,
    avatar: "/diverse-college-students.png",
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "c2",
    email: "jordan@college.edu",
    name: "Jordan Lee",
    role: "customer",
    walletBalance: 220,
    avatar: "/college-student-asian.jpg",
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "c3",
    email: "taylor@college.edu",
    name: "Taylor Smith",
    role: "customer",
    walletBalance: 180,
    avatar: "/college-student-person.jpg",
    createdAt: new Date("2024-01-18"),
  },
  {
    id: "c4",
    email: "morgan@college.edu",
    name: "Morgan Brown",
    role: "customer",
    walletBalance: 95,
    avatar: "/college-student-happy.jpg",
    createdAt: new Date("2024-01-22"),
  },
  {
    id: "c5",
    email: "casey@college.edu",
    name: "Casey Wilson",
    role: "customer",
    walletBalance: 310,
    avatar: "/college-student-smiling.jpg",
    createdAt: new Date("2024-02-01"),
  },
]

export const mockPurchases: Purchase[] = [
  { id: "pu1", customerId: "c1", productId: "p1", vendorId: "v1", amount: 45, createdAt: new Date("2024-03-01") },
  { id: "pu2", customerId: "c1", productId: "p2", vendorId: "v1", amount: 12, createdAt: new Date("2024-03-02") },
  { id: "pu3", customerId: "c1", productId: "p5", vendorId: "v3", amount: 60, createdAt: new Date("2024-03-03") },
  { id: "pu4", customerId: "c2", productId: "p3", vendorId: "v2", amount: 18, createdAt: new Date("2024-03-01") },
  { id: "pu5", customerId: "c2", productId: "p6", vendorId: "v3", amount: 25, createdAt: new Date("2024-03-02") },
  { id: "pu6", customerId: "c2", productId: "p7", vendorId: "v1", amount: 28, createdAt: new Date("2024-03-04") },
  { id: "pu7", customerId: "c2", productId: "p4", vendorId: "v2", amount: 35, createdAt: new Date("2024-03-05") },
  { id: "pu8", customerId: "c3", productId: "p1", vendorId: "v1", amount: 45, createdAt: new Date("2024-03-02") },
  { id: "pu9", customerId: "c3", productId: "p6", vendorId: "v3", amount: 25, createdAt: new Date("2024-03-03") },
  { id: "pu10", customerId: "c3", productId: "p8", vendorId: "v2", amount: 42, createdAt: new Date("2024-03-06") },
  { id: "pu11", customerId: "c4", productId: "p2", vendorId: "v1", amount: 12, createdAt: new Date("2024-03-01") },
  { id: "pu12", customerId: "c4", productId: "p3", vendorId: "v2", amount: 18, createdAt: new Date("2024-03-04") },
  { id: "pu13", customerId: "c5", productId: "p5", vendorId: "v3", amount: 60, createdAt: new Date("2024-03-01") },
  { id: "pu14", customerId: "c5", productId: "p6", vendorId: "v3", amount: 25, createdAt: new Date("2024-03-02") },
  { id: "pu15", customerId: "c5", productId: "p7", vendorId: "v1", amount: 28, createdAt: new Date("2024-03-03") },
  { id: "pu16", customerId: "c5", productId: "p1", vendorId: "v1", amount: 45, createdAt: new Date("2024-03-05") },
  { id: "pu17", customerId: "c5", productId: "p4", vendorId: "v2", amount: 35, createdAt: new Date("2024-03-06") },
]
